name: Laravel CI/CD

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'

    - name: Install dependencies
      run: composer install

    - name: Deploy to EC2
      run: |
        ssh-keyscan -H ${{ secrets.AWS_INSTANCE_IP }} >> ~/.ssh/known_hosts
        scp -r ./* ${{ secrets.EC2_USERNAME }}@${{ secrets.AWS_INSTANCE_IP }}:/var/www/html/
        ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.AWS_INSTANCE_IP }} "cd /var/www/html/Laravel10 && composer install && php artisan migrate --force"