name: Laravel Deployment
on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-20.04
    name: Deploy code
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Code deploy action step
        uses: ./github-action-script/
        id: deploy
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          application_name: 'laravel10'